version: '3'
services:

  db:
    restart: always
    image: postgres
    container_name: hitokoto_db_dev
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: hitokoto
      POSTGRES_PASSWORD: hitokoto
      POSTGRES_DB: hitokoto
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"

  redis:
    restart: always
    image: redis
    container_name: hitokoto_redis_dev
    ports:
      - 127.0.0.1:6379:6379
