version: '3'
services:
  app:
    restart: always
    #build: .
    image: candinya/hitokoto-go:latest
    container_name: hitokoto_go
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - internal_network
      - external_network
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_CONNECTION_STRING=postgres://hitokoto:hitokoto@db:5432/hitokoto
      - REDIS_CONNECTION_STRING=redis://redis:6379/0
      - MODE=prod
#    volumes: # Required when import data
#      - "./sentences-bundle:/app/sentences-bundle:ro"

  db:
    restart: always
    image: postgres
    container_name: hitokoto_db
    networks:
      - internal_network
    environment:
      POSTGRES_USER: hitokoto
      POSTGRES_PASSWORD: hitokoto
      POSTGRES_DB: hitokoto
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis
    container_name: hitokoto_redis
    networks:
      - internal_network
    volumes:
      - ./redis:/data

networks:
  internal_network:
    internal: true
  external_network:
