name: Hitokoto-Go Build Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ develop ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true
      -
        name: Build
        run: go build .
